### ISSUE TITLE
Client Get By username and password

### ISSUE THREAD

**Issue by h-rafiee** [SPIDER-L33T/geteset#1]
Hello My Friend thanks for your lib. it so helped to me.
but how can client get by username and password from my server?!

**Comment by SPIDER-L33T** [comment]
Hello.
From you server all clients will get updates without "username/password".

For example: You share updates on Windows server as "\\myserver\nodupdates".
In client`s settings "Update server" will be: \\myserver\nodupdates
and username/password fields will "blank", but in security settings for share folder "nodupdates" all users need "Read only" access.
